#+TITLE: Neighborhood Classes
#+AUTHOR: Hector F. Masson
#+EMAIL: h.masson1911@gmail.com



* Description
  In this file, we'll have all the classes involved in the neighborhhod counting and exploration. 
  The src blocks will be tangled to ../src/neigh-classes.lisp.


* Add the package to the tangled file
  #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
    (in-package :vrp)
  #+END_SRC


* Counting Solutions
** Basic solution
   This class represents a counting basic solution for the VRP, it is just a list of numbers where each number represents 
   the quantity of clients in the corresponding route.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
     (def-vrp-class counting-basic-solution ()
       ((num-clients) (routes))

       :documentation "A basic solution for counting."
       :constructor (new-counting-basic-solution)
       :print-object-string ("<counting-basic-solution ~a, ~a>" num-clients routes)
       :slots-for-obj= (num-clients routes))
   #+END_SRC
   
   #+begin_src lisp :export both :results output

     (let* ((s (new-counting-basic-solution 5 (list 2 3 5)))) 
       (format t "counting-solution ~a" s))

   #+end_src

   #+RESULTS:
   : counting-solution <counting-basic-solution 5, (2 3 5)>
   
* Neighborhood operations
  This classes represent the operations that are used to built the neighborhood criterion. An exception is /op-init/ 
  class, which represent the root node of the /neighborhood-tree/.

** Init operation
   This class represents an init operation, which is used to create the neighborhood-tree's root node.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
     (def-vrp-class counting-op-init ()
		()		

		:documentation "A class to initialize the 'root' of the neighborhood tree."
		:constructor (new-init-operation)
		:print-object-string ("<counting-op-init>")
		:slots-for-obj= ())
   #+END_SRC
   
   #+begin_src lisp :export both :results output

   (let* ((op (new-init-operation))) 
   (format t "~a" op))

   #+end_src

   #+RESULTS:
   : <counting-op-init>

** Select route operation
   This node represents a select route operation, where =route-symbol= is precisely 
   the name assigned to the selected route.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
     (def-vrp-class counting-op-select-route ()
       ((operation-id) (route-symbol))
       :documentation "A class to represent the select-route operation."
       :constructor (new-r-operation)
       :print-object-string ("<r-op id: ~a, route: ~a>" operation-id route-symbol)
       :slots-for-obj= (operation-id route-symbol))
   #+END_SRC

** Select client operation
   This node represents a select client operation, where =client-symbol= is precisely
   the name assigned to the client selected from the route named =route-symbol=.
   
   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp
     (def-vrp-class counting-op-select-client ()
       ((operation-id) (route-symbol) (client-symbol))
       :documentation "A class to represent the select-client operation."
       :constructor (new-a-operation)
       :print-object-string ("<a-op id: ~a, route: ~a, client: ~a>" operation-id route-symbol client-symbol)
       :slots-for-obj= (operation-id route-symbol client-symbol))
   #+END_SRC

** Insert client operation
   This node represents an insert client operation, where =client-symbol= is precisely
   the name corresponding to the client that is going to be inserted in the route named
   =route-symbol=.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
     (def-vrp-class counting-op-insert-client ()
       ((operation-id) (route-symbol) (client-symbol))
       :documentation "A class to represent the insert-client operation."
       :constructor (new-b-operation)
       :print-object-string ("<b-op id: ~a, route: ~a>, client: ~a" operation-id route-symbol client-symbol)
       :slots-for-obj= (operation-id route-symbol client-symbol))

   #+END_SRC

** Swap clients operation
   This node represents a swap clients operation, =client-1-symbol= and =client-2-symbol=
   correspond to the name of the clients that are going to be swapped.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
      (def-vrp-class counting-op-swap-clients ()
       ((operation-id) (client-1-symbol) (client-2-symbol))
       :documentation "A class to represent the swap-clients operation."
       :constructor (new-c-operation)
       :print-object-string ("<c-op id: ~a, client 1: ~a, client 2: ~a>" operation-id client-1-symbol client-2-symbol)
       :slots-for-obj= (operation-id client-1-symbol client-2-symbol))

   #+END_SRC

** Select subroute operation
   This node represents a select subroute operation, where =subroute-symbol= is precisely
   the name assigned to the subroute selected from the route named =route-symbol=.
   
   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
      (def-vrp-class counting-op-select-subroute ()
       ((operation-id) (route-symbol) (subroute-symbol))
       :documentation "A class to represent the select-subroute operation."
       :constructor (new-e-operation)
       :print-object-string ("<e-op id: ~a, route: ~a, subroute: ~a>" operation-id route-symbol subroute-symbol)
       :slots-for-obj= (operation-id route-symbol subroute-symbol))
   #+END_SRC

** Insert subroute operation
   This node represents an insert subroute operation, where =subroute-symbol= is precisely
   the name corresponding to the subroute that is going to be inserted in the route named
   =route-symbol=.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
      (def-vrp-class counting-op-insert-subroute ()
       ((operation-id) (route-symbol) (subroute-symbol))
       :documentation "A class to represent the insert-subroute operation."
       :constructor (new-f-operation)
       :print-object-string ("<f-op id: ~a, route: ~a, subroute: ~a>" operation-id route-symbol subroute-symbol)
       :slots-for-obj= (operation-id route-symbol subroute-symbol))

   #+END_SRC

** Swap subroutes operation
   This node represents a swap subroutes operation, =subroute-1-symbol= and =subroute-2-symbol=
   correspond to the name of the subroutes that are going to be swapped.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
      (def-vrp-class counting-op-swap-subroutes ()
       ((operation-id) (subroute-1-symbol) (subroute-2-symbol))
       :documentation "A class to represent the swap-subroutes operation."
       :constructor (new-g-operation)
       :print-object-string ("<r-op id: ~a, subroute 1: ~a, subroute 2: ~a>" operation-id subroute-1-symbol subroute-2-symbol)
       :slots-for-obj= (operation-id route-symbol subroute-2-symbol))

   #+END_SRC
** Reverse subroute operation
   This node represents an reverse subroute operation, where =subroute-symbol= is precisely
   the name corresponding to the subroute that is going to be reversed.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
      (def-vrp-class counting-op-reverse-subroute ()
       ((operation-id) (subroute-symbol))
       :documentation "A class to represent the reverse-subroute operation."
       :constructor (new-h-operation)
       :print-object-string ("<h-op id: ~a, subroute: ~a>" operation-id subroute-symbol)
       :slots-for-obj= (operation-id subroute-symbol))

   #+END_SRC

   
* Neighborhood-tree nodes
  This classes represent nodes of the /neighborhood-tree/. Each one of these has a corresponding neighborhood operation that it represents, with the exception of =root-node= and =nil-node= which represents particular concepts for constructing and counting over it. We'll explain what these nodes represent later.

  This /neighborhood-tree/ has stored all the information of the neighborhood generated by applying the neighborhood criterion to the current solution given, this mean that every further analysis that is wanted to be done for this neighborhood can be done by processing this tree. 

  Is important to state that the way in which this tree stores the resulting neighborhood, is by instantiating values for the neighborhood operations in the criterion, more clearly: by adding the corresponding node to the tree.

** Description
   Each tree node has four attributes: node-id (is the node identifier in the branch), total-count (represents the total amount of neighbors down this node in the tree), parent-node (is a reference to the parent node in the tree) and index-at-parent (since some nodes can have multiple children this value represents the position corresponding in that list for the current node, this value is 1-base indexed).

   Note that root-node and nil-node, since they are especial nodes they don't necessarily follow the previous rule.

** root-node
   This node represents the neighborhood-tree's root node, it contains the total number of neighbors and a child node 
   which is the tree node corresponding with the first neigborhood operation in the criterion.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
     (def-vrp-class root-node ()
       ((node-id) (total) (child)) 
       :documentation "A class to represent a root-node in the neighberhood-tree."
       :constructor (new-root-node)
       :print-object-string ("<root-node id: ~a, count: ~a, child: ~a>" node-id total child)
       :slots-for-obj= (node-id total child))

   #+END_SRC

** r-node
   This node represents the select route operation in the /neighborhood-tree/. The attribute /children-list/ represents
   a list of pairs with a child node as its first element and the number of the route that was selected for that subtree
   as its second element.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
     (def-vrp-class r-node ()
       ((node-id     :initarg :node-id
		     :initform 0)
	(total	 :initform 0)
	(parent	 :initarg :parent
		      :initform nil)
	(at-parent     :initarg :at-parent
		       :initform 1)
	;; a list of pairs (child . route-number)
	(children   :initform nil)) 
       :documentation "A class to represent a select-root operation in the neighberhood-tree."
       :constructor (new-r-node)
       :print-object-string ("<r-node id: ~a, count: ~a, parent: ~a, at-parent: ~a>" node-id total parent at-parent)
       :slots-for-obj= (node-id total parent at-parent children)
       :slots-for-clone (node-id total parent at-parent children))

   #+END_SRC

** a-node
   This node represents the select client operation in the /neighborhood-tree/. The attribute /route-number/
   represents the route from which the client will be selected. The attribute /possibilities-at-node/
   represents the number of clients in that route.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 

     (def-vrp-class a-node ()
       ((node-id  :initarg :node-id
		  :initform 0)
	(total :initform 0)
	(parent :initarg :parent
		:initform nil)
	(at-parent     :initarg :at-parent
		       :initform 1)
	(route-number  :initarg :route-number)
	(possibilities   :initform 0)
	;; a list of pairs (child . route-number)
	(child   :initform nil)) 
       :documentation "A class to represent a select-client operation in the neighberhood-tree."
       :constructor (new-a-node)
       :print-object-string ("<a-node id: ~a, count: ~a, parent: ~a, at-parent: ~a>" node-id total parent at-parent)
       :slots-for-obj= (node-id total parent at-parent route-number possibilities child)
       :slots-for-clone (node-id total parent at-parent route-number possibilities child))

   #+END_SRC

** b-node
   This node represents the insert client operation in the /neighborhood-tree/. The attribute /route-number/
   represents the route in which the client will be inserted. The attribute /possibilities-at-node/ represents
   the number of positions at which the selected client can be inserted, this quantity is equal to the number
   of clients in the selected route plus one.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
	 (def-vrp-class b-node ()
	   ((node-id  :initarg :node-id
		      :initform 0)
	    (total :initform 0)
	    (parent :initarg :parent
		    :initform nil)
	    (at-parent     :initarg :at-parent
			   :initform 1)
	    (route-number  :initarg :route-number)
	    (possibilities   :initform 0)
	    (select-op-id :initarg :select-op-id)
	    ;; a list of pairs (child . route-number)
	    (child   :initform nil)) 
	   :documentation "A class to represent an insert-client operation in the neighberhood-tree."
	   :constructor (new-b-node)
	   :print-object-string ("<b-node id: ~a, count: ~a, parent: ~a, at-parent: ~a>" node-id total parent at-parent)
	   :slots-for-obj= (node-id total parent at-parent route-number possibilities select-op-id child)
	   :slots-for-clone (node-id total parent at-parent route-number possibilities select-op-id child))

   #+END_SRC   
   
** c-node
   This node represents the swap clients operation in the /neighborhood-tree/. The attributes
   /select-op1-id/ and /select-op2-id/, represent the indentifier of the select client
   operations.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
	 (def-vrp-class c-node ()
	   ((node-id  :initarg :node-id
		      :initform 0)
	    (total :initform 0)
	    (parent :initarg :parent
		    :initform nil)
	    (at-parent :initarg :at-parent
		       :initform 1)
	    (select-op1-id :initarg :select-op1-id)
	    (select-op2-id :initarg :select-op2-id)
	    (child   :initform nil)) 
	   :documentation "A class to represent a swap-clients operation in the neighberhood-tree."
	   :constructor (new-c-node)
	   :print-object-string ("<c-node id: ~a, count: ~a, parent: ~a, at-parent: ~a>" node-id total parent at-parent)
	   :slots-for-obj= (node-id total parent at-parent select-op1-id select-op2-id child)
	   :slots-for-clone (node-id total parent at-parent select-op1-id select-op2-id child))

   #+END_SRC

** e-node
   This node represents the select client operation in the /neighborhood-tree/. The attribute /children-list/ represents
   a list of pairs with a child node as its first element and a pair, with the length and available positions for the 
   selected subroute, as the second element.
   
   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
	 (def-vrp-class e-node ()
	   ((node-id  :initarg :node-id
		      :initform 0)
	    (total :initform 0)
	    (parent :initarg :parent
		    :initform nil)
	    (at-parent :initarg :at-parent
		       :initform 1)
	    (route-number :initarg :route-number)
	    ;; a list of pairs (child . (subroute-len . positions))
	    (children :initform nil)) 
	   :documentation "A class to represent a select-subroute operation in the neighberhood-tree."
	   :constructor (new-e-node)
	   :print-object-string ("<e-node id: ~a, count: ~a, parent: ~a, at-parent: ~a>" node-id total parent at-parent)
	   :slots-for-obj= (node-id total parent at-parent route-number children)
	   :slots-for-clone (node-id total parent at-parent route-number children))

   #+END_SRC

** f-node
   This node represents the select client operation in the /neighborhood-tree/. The attribute /possibilities-at-node/
   represents the number of positions at which the selected subroute can be inserted, this quantity is equal to the 
   number of clients in the selected route plus one.
   
   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
     (def-vrp-class f-node ()
       ((node-id  :initarg :node-id
		  :initform 0)
	(total :initform 0)
	(parent :initarg :parent
		:initform nil)
	(at-parent :initarg :at-parent
		   :initform 1)
	(route-number :initarg :route-number)
	;; a list of pairs (child . (subroute-len . positions))
	(possibilities :initform 0)
	(select-op-id :initarg :select-op-id)
	(child :initform nil)) 
       :documentation "A class to represent an insert-subroute operation in the neighberhood-tree."
       :constructor (new-f-node)
       :print-object-string ("<e-node id: ~a, count: ~a, parent: ~a, at-parent: ~a>" node-id total parent at-parent)
       :slots-for-obj= (node-id total parent at-parent route-number possibilities select-op-id child)
       :slots-for-clone (node-id total parent at-parent route-number possibilities select-op-id child))


   #+END_SRC

** g-node
   This node represents the swap subroutes operation in the /neighborhood-tree/. The attributes
   /select-op1-id/ and /select-op2-id/, represent the indentifier of the select subroute
   operations.   


   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
     (def-vrp-class g-node ()
       ((node-id  :initarg :node-id
		  :initform 0)
	(total :initform 0)
	(parent :initarg :parent
		:initform nil)
	(at-parent :initarg :at-parent
		   :initform 1)
	(select-op1-id :initarg :select-op1-id)
	(select-op2-id :initarg :select-op2-id)
	(child   :initform nil))  
       :documentation "A class to represent a swap-subroutes operation in the neighberhood-tree."
       :constructor (new-g-node)
       :print-object-string ("<e-node id: ~a, count: ~a, parent: ~a, at-parent: ~a>" node-id total parent at-parent)
       :slots-for-obj= (node-id total parent at-parent select-op1-id select-op2-id child)
       :slots-for-clone (node-id total parent at-parent select-op1-id select-op2-id child))

   #+END_SRC
** h-node
   This node represents the reverse subroute operation in the /neighborhood-tree/. The attribute
   /select-op-id/, represent the indentifier of the select subroute operation.   


   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
	  (def-vrp-class h-node ()
	    ((node-id  :initarg :node-id
		       :initform 0)
	     (total :initform 0)
	     (parent :initarg :parent
		     :initform nil)
	     (at-parent :initarg :at-parent
			:initform 1)
	     (select-op-id :initarg :select-op-id)
	     (child :initform nil))   
	    :documentation "A class to represent a reverse-subroute operation in the neighberhood-tree."
	    :constructor (new-h-node)
	    :print-object-string ("<e-node id: ~a, count: ~a, parent: ~a, at-parent: ~a>" node-id total parent at-parent)
	    :slots-for-obj= (node-id total parent at-parent select-op-id child)
	    :slots-for-clone (node-id total parent at-parent select-op-id child))

   #+END_SRC

** nil-node
   This node represents a leaf of the /neighborhood-tree. It works as the neutral element for the operation defined by 
   the parent node.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
	       (def-vrp-class nil-node ()
		 ((total :initform 0
			 :initarg :total-count)
		  (parent :initarg :parent
			  :initform nil)
		  (at-parent :initarg :at-parent
			     :initform 1))   
		 :documentation "A class to represent a nil-node in the neighberhood-tree."
		 :constructor (new-nil-node)
		 :print-object-string ("<nil-node count: ~a, parent: ~a, at-parent: ~a>" total parent at-parent)
		 :slots-for-obj= (total parent at-parent)
		 :slots-for-clone (total parent at-parent))

   #+END_SRC

* Neighborhood API
  In this section, I'll define a class to store the /neighboerhood-tree/,
  previously computed information and perform some operations over the
  /neighborhood-tree/.

** Description
   Here we'll define some classes that works as an API for the system.

** Search state
   Here I'll define a class that stores the exploration state in a set if neighbor solutions.
   This class has to store some attributes like:
   
   - number of solutions that have been processed
   - a hash function that traces some chages in the order of the solutions
     
   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
     (def-vrp-class search-state ()
       ((number-of-analysed-solutions :initform 0)
	(solution-mapper :initarg :solution-mapper
			 :initform (make-hash-table)))
       :documentation "A class that stores the state of a search over a set of solutions."
       :constructor (new-search-state)
       :print-object-string ("<search-state, analysed-solutions: ~a>" number-of-analysed-solutions)
       :slots-for-obj= (number-of-analysed-solutions solution-mapper)
       :slots-for-clone (number-of-analysed-solutions solution-mapper))

   #+END_SRC
** Basic Region
   A basic region its just a branch in the neighborhood tree.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
	  (def-vrp-class neighborhood-basic-region ()
	    ((first-index :initarg :first-index
			    :initform nil)
	       (info :initarg :info)
	       (subtree-sols :initarg :subtree-sols
			     :initform 0)
	       (cardinality :initarg :cardinality
			    :initform 0))
	    :documentation "A class that represents a basic region in the neighborhood."
	    :constructor (new-neighborhood-region)
	    :print-object-string ("<neighborhood-basic-region, first-index: ~a, info: ~a, cardinality: ~a>" first-index info cardinality)
	    :slots-for-obj= (first-index info subtree-sols cardinality)
	    :slots-for-clone (first-index info subtree-sols cardinality))

   #+END_SRC

** Region
   In this section I'll define a class that represents a region in the neighborhood.
   This is defined as a set of basic solutions.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
	  (def-vrp-class neighborhood-region ()
		((number-id :initarg :number-id)
		 (index-range :initarg :index-range)
		 (cardinality :initarg :cardinality
			      :initform 0)
		 (basic-region-list :initarg :basic-region-list
				    :initform nil)
		 (basic-indexes :initarg :basic-indexes
				:initform nil)
		 (basic-keys :initarg :basic-keys
			     :initform nil)
		 (search-state :initform (make-instance 'search-state))
		 (neighborhood :initarg :neighborhood
			       :initform nil))
	    :documentation "A class that represents a region in the neighborhood."
	    :constructor (new-neighborhood-region)
	    :print-object-string ("<neighborhood-region, number-id: ~a, index-range: ~a, cardinality: ~a, neighborhood: ~a>" number-id index-range cardinality neighborhood)
	    :slots-for-obj= (number-id index-range cardinality basic-region-list basic-indexes basic-keys search-state neighborhood)
	    :slots-for-clone (number-id index-range cardinality basic-region-list basic-indexes basic-keys search-state neighborhood))


   #+END_SRC
** Neighborhood-tree
   Here we define a the neighborhod, and contains the problem, solutions and criteria
   that it represents. In addition, other important features are stored and defined
   with the goal of only compute them once.

   #+BEGIN_SRC lisp +n -r :results none :exports code :tangle ../src/neigh-classes.lisp 
	  (def-vrp-class neighborhood-tree ()
		((problem :initarg :problem
			  :initform nil)
		 (solution :initarg :solution)
		 (criterion :initarg :criterion)
		 (counting-solution :initarg :counting-solution)
		 (tree :initarg :tree)
		 (cardinality :initarg :cardinality 
			      :initform 0)
		 (number-of-regions :initform nil)
		 (region-list :initarg :region-list
			      :initform nil)
		 (region-indexes :initarg :region-indexes
				 :initform nil)
		 (region-keys :initarg :region-keys
			      :initform nil)
		 (search-state :initform (make-instance 'search-state)))
	    :documentation "A class that works as an API for the neighborhood-tree."
	    :constructor (new-neighborhood-tree)
	    :print-object-string ("<neighborhood-tree, problem: ~a, solution: ~a, criterion: ~a, counting-solution: ~a, cardinality: ~a>" problem solution criterion counting-solution cardinality)
	    :slots-for-obj= (problem solution criterion counting-solution tree cardinality number-of-regions region-list region-indexes region-keys search-state)
	    :slots-for-clone (problem solution criterion counting-solution tree cardinality number-of-regions region-list region-indexes region-keys search-state))

   #+END_SRC

