(dolist (f (list "src/vrp-package.lisp"
		 "src/vrp-utilities.lisp"
		 "src/vrp-random-number-generation.lisp"
		 "src/vrp-generic-functions.lisp"
		 "src/vrp-class-definition-macro.lisp"
		 "src/vrp-classes.lisp"
		 "src/vrp-moments.lisp"
		 "src/vrp-data.lisp"
		 "src/vrp-neighborhood-exploration-macros.lisp"
		 "src/vrp-neighborhood-simulation.lisp"
		 "src/vrp-neighborhood-operations.lisp"
		 "src/vrp-delta-cost.lisp"
		 ;;		      "src/vrp-search-strategies.lisp"

		 "src/neigh-configuration.lisp"
		 "src/neigh-utilities.lisp"     
		 "src/neigh-class-macros.lisp"
		 "src/neigh-classes.lisp"
		 "src/neigh-generic-functions.lisp"
		 "src/neigh-criterion.lisp"
		 "src/neigh-cardinality.lisp"
		 "src/neigh-indexer.lisp"
		 "src/neigh-compatibility.lisp"
		 "src/neigh-exploration.lisp"
		 "src/neigh-exploration-heuristics.lisp"
		 "src/neigh-strategies.lisp"

		 "src/neigh-statistics.lisp"

		 "src/eval-classes.lisp"
		 "src/eval-methods.lisp"
		 "src/eval-graph-builder.lisp"

		 "src/prefabs-classes.lisp"
		 "src/prefabs-functions.lisp"
		 "src/prefabs-tutorials.lisp"

		 "src/vrp-criteria.lisp"
		 "src/vrp-algorithms.lisp"
		 ;;		      "data/vrp-data-a-n32-k5.lisp"
		 ;;		      "data/vrp-data-a-n33-k5.lisp"
		 ;;		      "data/vrp-data-a-n33-k6.lisp"
		 ;;		      "data/vrp-data-a-n37-k5.lisp"
		 ;;		      "data/vrp-data-a-n65-k9.lisp"
		 ;;		      "data/vrp-data-a-n80-k10.lisp"
		 ;;		      "data/vrp-data-f-n135-k7.lisp"
		 ;;
		 ;;		      "data/neigh-data.lisp"
		 ;;		      "src/neigh-algorithms.lisp"
		 ))
  (format t "Loading ~a...~%" f)
  (load f))
